version: '3.4'

services:
  catalog.db:
    image: postgres

  basket.db:
    image: postgres

  distributedcache:
    image: redis

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:

